# Generated by Django 4.2.26 on 2026-01-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='infected_upload_count',
            field=models.IntegerField(default=0),
        ),
    ]
