# Generated by Django 4.2.26 on 2026-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ban_expires_at_user_ban_reason_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
