# Generated by Django 4.2.26 on 2026-01-15 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='schematics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['schematic', 'schem', 'litematic', 'nbt'])])),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('minecraft_version', models.CharField(blank=True, max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('block_count', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending Scan'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan Error')], db_index=True, default='pending', max_length=20)),
                ('scan_result', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('preview_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchematicComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchematicVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='schematic_versions/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('version_number', models.IntegerField()),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schematics.schematic')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SchematicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='schematics.schematic')),
            ],
        ),
    ]
