# Generated by Django 4.2.26 on 2026-01-15 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schematics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematiclike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schematiccomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='schematics.schematiccomment'),
        ),
        migrations.AddField(
            model_name='schematiccomment',
            name='schematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schematics.schematic'),
        ),
        migrations.AddField(
            model_name='schematiccomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schematic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schematic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='schematics', to='schematics.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='schematicversion',
            unique_together={('schematic', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='schematiclike',
            unique_together={('user', 'schematic')},
        ),
        migrations.AddIndex(
            model_name='schematic',
            index=models.Index(fields=['-created_at'], name='schematics__created_d8b58a_idx'),
        ),
        migrations.AddIndex(
            model_name='schematic',
            index=models.Index(fields=['owner', '-created_at'], name='schematics__owner_i_877544_idx'),
        ),
        migrations.AddIndex(
            model_name='schematic',
            index=models.Index(fields=['scan_status'], name='schematics__scan_st_aa464f_idx'),
        ),
    ]
