# Generated by Django 4.2.26 on 2026-01-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematic',
            name='max_scan_retries',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='schematic',
            name='scan_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
