# Generated by Django 4.2.26 on 2026-01-16 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0003_add_scan_retry_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchematicImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(
                    upload_to='schematic_images/%Y/%m/%d/',
                    validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]
                )),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schematics.schematic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schematicimage',
            index=models.Index(fields=['schematic', 'order'], name='schematics_schematicimage_sch_order_idx'),
        ),
    ]
